// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCag57KOV_GHeLAFLSn6_AOmZj066udL8A',
    appId: '1:1028898398223:web:38676728e6ba9464c7037a',
    messagingSenderId: '1028898398223',
    projectId: 'spotifyclone-c0f1d',
    authDomain: 'spotifyclone-c0f1d.firebaseapp.com',
    storageBucket: 'spotifyclone-c0f1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5FHZawLg63jP4DMh8F0YZ0ngHzY_UU9Q',
    appId: '1:1028898398223:android:94f3ca8c023d4285c7037a',
    messagingSenderId: '1028898398223',
    projectId: 'spotifyclone-c0f1d',
    storageBucket: 'spotifyclone-c0f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDatGYoy08ysuGjtJNOE9u8B6v679vsw0Y',
    appId: '1:1028898398223:ios:ad955fb3be0604fec7037a',
    messagingSenderId: '1028898398223',
    projectId: 'spotifyclone-c0f1d',
    storageBucket: 'spotifyclone-c0f1d.appspot.com',
    iosBundleId: 'com.emrekirik.spotifycloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDatGYoy08ysuGjtJNOE9u8B6v679vsw0Y',
    appId: '1:1028898398223:ios:ad955fb3be0604fec7037a',
    messagingSenderId: '1028898398223',
    projectId: 'spotifyclone-c0f1d',
    storageBucket: 'spotifyclone-c0f1d.appspot.com',
    iosBundleId: 'com.emrekirik.spotifycloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCag57KOV_GHeLAFLSn6_AOmZj066udL8A',
    appId: '1:1028898398223:web:9550603f999d6252c7037a',
    messagingSenderId: '1028898398223',
    projectId: 'spotifyclone-c0f1d',
    authDomain: 'spotifyclone-c0f1d.firebaseapp.com',
    storageBucket: 'spotifyclone-c0f1d.appspot.com',
  );
}
